/**
 * @description       : 
 * @author            : timothy-james.guela@viseo.com
 * @group             : 
 * @last modified on  : 05-13-2026
 * @last modified by  : timothy-james.guela@viseo.com
**/
public with sharing class handlerSampleClass {
    public static void validateEmailSubject(EmailMessage emailMsg) {
        // some cases require to query pa yung sobject kasi ID lang ibabato
        // in this case pwede na diretsyo
        
    }
}